/**
 * Customize sitemap items generated by VitePress.
 * Adjusts changefreq and priority based on page depth.
 */
export function createSitemapItems(items) {
  return items.map((item) => {
    const depth = item.url.split('/').filter(Boolean).length

    if (depth === 0 || item.url === 'en-US/') {
      item.changefreq = 'weekly'
      item.priority = 1.0
    } else if (depth <= 2) {
      item.changefreq = 'weekly'
      item.priority = 0.8
    } else {
      item.changefreq = 'monthly'
      item.priority = 0.6
    }

    return item
  })
}
