import { execSync } from 'node:child_process'

/**
 * Get the last git commit date for a file.
 * Falls back to current date if git is unavailable.
 */
function getLastModified(filePath) {
  try {
    const date = execSync(`git log -1 --format=%cI -- "${filePath}"`, {
      encoding: 'utf-8',
      stdio: ['pipe', 'pipe', 'ignore']
    }).trim()
    return date || new Date().toISOString()
  } catch {
    return new Date().toISOString()
  }
}

/**
 * Customize sitemap items generated by VitePress.
 * Adjusts changefreq, priority, and lastmod based on page depth and git history.
 */
export function createSitemapItems(items) {
  return items.map((item) => {
    const depth = item.url.split('/').filter(Boolean).length

    if (depth === 0 || item.url === 'en-US/') {
      item.changefreq = 'weekly'
      item.priority = 1.0
    } else if (depth <= 2) {
      item.changefreq = 'weekly'
      item.priority = 0.8
    } else {
      item.changefreq = 'monthly'
      item.priority = 0.6
    }

    // Convert URL path back to source file path for git lookup
    const sourcePath = item.url
      .replace(/\.html$/, '.md')
      .replace(/\/$/, '/index.md')
    item.lastmod = getLastModified(sourcePath)

    return item
  })
}
